name: Deploy to AWS S3 and CloudFront

on:
  push:
    branches:
      - main  # or your default branch name
  # Allow manual triggers from the Actions tab
  workflow_dispatch:

# Limit permissions for GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Use protected environment
    
    # Prevent concurrent deployments
    concurrency: 
      group: production
      cancel-in-progress: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Clean install dependencies
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install -g eslint
        env:
          NODE_ENV: production
          NPM_CONFIG_AUDIT: true

      - name: Run linting
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true  # Hide AWS account ID in logs

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Create CloudFront invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 